
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ozone-operator
  namespace: rook-ozone-system
  labels:
    app: rook-ozone-operator
spec:
  selector:
    matchLabels:
      app: rook-ozone-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: rook-ozone-operator
    spec:
      serviceAccountName: rook-ozone-operator
      containers:
      - name: rook-ozone-operator
        image: elek/rook-ozone
        imagePullPolicy: Always
        args:
        - ozone
        - operator
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
