---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: objectstores.ozone.rook.io
spec:
  group: ozone.rook.io
  names:
    kind: ObjectStore
    listKind: ObjectStoreList
    plural: objectstores
    singular: objectstore
  scope: Namespaced
  version: v1alpha1
---
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ozone-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ozone-operator
  namespace: rook-ozone-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: rook-ozone-operator
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - secrets
  - pods
  - services
  - configmaps
  verbs:
  - get
  - watch
  - create
  - update
- apiGroups:
  - apps
  resources:
  - statefulsets
  - daemonsets
  verbs:
  - get
  - create
  - update
- apiGroups:
  - ozone.rook.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - rook.io
  resources:
  - '*'
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ozone-operator
  namespace: rook-ozone-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ozone-operator
subjects:
- kind: ServiceAccount
  name: rook-ozone-operator
  namespace: rook-ozone-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ozone-operator
  namespace: rook-ozone-system
  labels:
    app: rook-ozone-operator
spec:
  selector:
    matchLabels:
      app: rook-ozone-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: rook-ozone-operator
    spec:
      serviceAccountName: rook-ozone-operator
      containers:
      - name: rook-ozone-operator
        image: elek/rook-ozone
        imagePullPolicy: Always
        args:
        - ozone
        - operator
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
